[versions]
shadow = "9.3.0"
paper-yml = "0.8.0"
minotaur = "2.8.10"

paper-api = "1.21.11-R0.1-SNAPSHOT"
voicechat-api = "2.6.0"
lavaplayer = "2.2.6"
youtube-source = "1.17.0"
protocol-lib = "5.4.0"
commandapi = "11.1.0"
commons-io = "2.21.0"
bstats = "3.1.0"
snakeyaml = "2.5"
simple-yaml = "1.8.4"
lombok = "1.18.36"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
paper-yml = { id = "de.eldoria.plugin-yml.paper", version.ref = "paper-yml" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
voicechat-api = { module = "de.maxhenkel.voicechat:voicechat-api", version.ref = "voicechat-api" }
protocollib = { module = "net.dmulloy2:ProtocolLib", version.ref = "protocol-lib" }
commandapi = { module = "dev.jorel:commandapi-paper-core", version.ref = "commandapi" }

lavaplayer = { module = "dev.arbjerg:lavaplayer", version.ref = "lavaplayer" }
lavaplayer-youtube = { module = "dev.lavalink.youtube:common", version.ref = "youtube-source" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
simple-yaml = { module = "me.carleslc.Simple-YAML:Simple-Yaml", version.ref = "simple-yaml" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
